### ISSUE TITLE
documentation for account.hasAccount and account.hasAnonymousAccount

### ISSUE THREAD

**Issue by bbn** [hoodiehq-archive/hood.ie-website-old#11]
It is frequently the case that on page load we'd like to know if a user is logged in or not. I had to dig a bit in the code to find account.hasAccount and account.hasAnonymousAccount. These ought to be documented.

**Comment by gr2m** [comment]
hey @bbn, so sorry to get back to you that late, we've overseen your question!

so yes, [hoodie.account.hasAccount()](http://hoodiehq.github.io/hoodie.js/doc/core/account.html#hasaccount) checks if your user has the username set, which is the current way to find out if the user is currently signed in or not.

the `hasAnonymousAccount()` and `anonymousSignUp` are rather used internally. For example, a user doesn't have an account but wants to share data with others, an anonymous account gets created internally to start the synchronization with the central database, so our workers can pickup the share and react on it. If the user creates an account later using `account.signUp`, we don't create another account, but make an upgrade of the anonymous account internally. Sounds complex, cause it is ;-)

But your question made as wonder, if `hasAccount()` is the right method to find out if a user is signed in. It returns true when the user's data gets synchronized, be it because he signed up, or because an anonymous account has been created for him. 

So to relate to your question, `account.hasAccount()` may return true, although the user never actively signed in. And we wonder if that might be confusing?

**Comment by espy** [comment]
By the way, you can use `hoodie.account.username` if you just want to quickly check whether and who is currently logged in.

**Comment by janl** [comment]
closing in favour of https://github.com/hoodiehq/documentation/issues/18
