### ISSUE TITLE
add instructions for deploying hoodie to OpenShift

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq-archive/hood.ie-website-old#22]
https://github.com/ryanj/nodejs-custom-version-openshift#nodejs-on-openshift

OpenShift has a free tier, is relatively easy to use and also gives you 1GB of real hard drive space (so you could conceivably run couch on it too, or leveldb)

**Comment by ninor** [comment]
I'll add to this "petition"

There are a couple of resources that could be useful for this task:

Here's a CouchDB script to install it in an openshift instance:
https://github.com/marianoguerra/couchdb-for-openshift

Or, maybe instead of some instructions, it would be better to have an openshift cartridge/quickstart for hood.ie:

Quickstarts:
https://www.openshift.com/developers/get-involved/creating-quickstarts
Cartridges:
http://openshift.github.io/documentation/oo_cartridge_developers_guide.html

**Comment by janl** [comment]
@ninor would you be interested in writing down the Hoodie specific instructions?

**Comment by ninor** [comment]
I could try!

**Comment by ninor** [comment]
Unfortunately it seems that the linked script timeouts after some time building, and I have tried several times, but it doesn't finish properly.
Anybody can try it?

**Comment by ninor** [comment]
Good news, the openshift team has in its queue the development of a CouchDB cartridge!
It's in the NEW column, not yet about to begin, but anybody interested can leave a message and subscribe to that card news.

https://trello.com/c/Iid6N299/18-create-a-couchdb-cartridge

**Comment by janl** [comment]
losing in favour of https://github.com/hoodiehq/documentation/issues/17

**Comment by ramka001** [comment]
Hi May I have a look at the trello.com  couchdb cartridge ?
